version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
      - pip install pycodestyle
  build:
    commands:
      - echo "No issues found!"
      - python -m pytest