version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
      - pip install pycodestyle
  build:
    commands:
      - pycodestyle -v hello.py
      - echo "pycodestyle found no issues!"
      - python -m pytest